services:
  nginx:
    build: .
    image: nginx:1.25-alpine
    container_name: infario-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /deployments/:/deployments:ro
      - ${HOME}:${HOME}:ro
    restart: unless-stopped
